import { DB, DAYTRIP_EXCLUDE, PER_NIGHT, WARNINGS } from './db.js';
import { bindAdminCommunicationPanel, renderAdminCommunicationPanel } from './communications.js';

let password = ''; let draft = null; let dirty = false;
const clone = value => structuredClone(value);
const itemLists = data => [data.base, data.laundry, ...Object.values(data.weather), ...Object.values(data.transport), ...Object.values(data.extra)];
const TRANSPORT_MODES = [['tutti','Tutti i mezzi'],['car','Auto'],['motorcycle','Moto'],['plane','Aereo'],['train','Treno'],['camper','Camper'],['walking','A piedi / trekking']];
const WEATHER_MODES = [['tutti','Tutti i meteo'],['sun','Sole'],['rain','Pioggia'],['cold','Freddo']];
const normalizeTransportMode = mode => ({ auto:'car', macchina:'car', auto_macchina:'car', moto:'motorcycle', aereo:'plane', treno:'train', treno_regionale:'train', backpack:'walking', zaino:'walking', viaggio_zaino:'walking', trekking:'walking', a_piedi_trekking:'walking' }[mode] || mode);
const defaultQuantityRule = item => item.q === 'n' ? {type:'perDay',base:1,every:1,min:1,max:0,laundry:true} : {type:'fixed',base:1,every:1,min:1,max:0,laundry:false};
const payload = () => ({ db: draft.db, daytripExclude: draft.daytripExclude, perNight: draft.perNight, warningMessages: draft.warningMessages });
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function initAdmin() {
  document.getElementById('adminOpen')?.addEventListener('click', openLogin);
}
function shell(title, body) {
  document.getElementById('adminModal')?.remove();
  document.body.insertAdjacentHTML('beforeend', `<div class="admin-modal" id="adminModal"><section class="admin-panel" role="dialog" aria-modal="true"><header><div><small>PACKLIST PRO</small><h2>${title}</h2></div><button class="admin-close" aria-label="Chiudi">×</button></header>${body}</section></div>`);
  const modal=document.getElementById('adminModal'); modal.querySelector('.admin-close').onclick=()=>{if(!dirty||confirm('Chiudere e perdere le modifiche non salvate?')){password='';draft=null;dirty=false;modal.remove()}};
}
function openLogin() {
  shell('Accesso amministratore', `<form id="adminLogin" class="admin-login"><label>Password<span class="admin-password"><input name="password" type="password" required autocomplete="current-password"><button type="button" id="adminPasswordToggle" aria-label="Mostra password">👁</button></span></label><button class="btn-sm">Apri pannello</button><p class="admin-status"></p></form>`);
  document.getElementById('adminPasswordToggle').onclick=()=>{const input=document.querySelector('#adminLogin input');input.type=input.type==='password'?'text':'password';document.getElementById('adminPasswordToggle').setAttribute('aria-label',input.type==='password'?'Mostra password':'Nascondi password')};
  document.getElementById('adminLogin').onsubmit = async e => { e.preventDefault(); const candidate=String(new FormData(e.target).get('password')||''); const status=e.target.querySelector('.admin-status'); const button=e.submitter||e.target.querySelector('button[type=submit],button:not([type])'); button.disabled=true; status.textContent='Verifica credenziali…'; try { const response=await fetch('/api/admin-auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:candidate})}); const data=await response.json().catch(()=>({})); if(!response.ok||data.ok!==true)throw new Error('Password non valida'); password=candidate; draft={db:clone(DB),daytripExclude:[...DAYTRIP_EXCLUDE],perNight:[...PER_NIGHT],warningMessages:WARNINGS.map(w=>w.msg)}; itemLists(draft.db).flat().forEach(item => { item.worn = Boolean(item.worn); item.bulk = Number(item.bulk || 1); item.transportModes = Array.isArray(item.transportModes) && item.transportModes.length ? [...new Set(item.transportModes.map(normalizeTransportMode))] : ['tutti']; if(item.transportModes.includes('tutti'))item.transportModes=['tutti']; item.weatherModes=Array.isArray(item.weatherModes)&&item.weatherModes.length?[...new Set(item.weatherModes)]:['tutti'];if(item.weatherModes.includes('tutti'))item.weatherModes=['tutti']; item.quantityRule={...defaultQuantityRule(item),...(item.quantityRule||{})}; }); dirty=false; render(); } catch(error) { password='';draft=null;status.textContent=error.message==='Password non valida'?error.message:'Verifica password non riuscita';button.disabled=false; } };
}
const pathList = () => [['Base','base'],['Laundry','laundry'],...Object.keys(draft.db.weather).map(k=>[`Weather · ${k}`,`weather.${k}`]),...Object.keys(draft.db.transport).map(k=>[`Transport · ${k}`,`transport.${k}`]),...Object.keys(draft.db.extra).map(k=>[`Attività · ${k}`,`extra.${k}`])];
const getList = path => path.split('.').reduce((o,k)=>o[k],draft.db);
const field = (label, control, help = '') => `<label class="admin-field"><span>${label}${help ? `<small>${help}</small>` : ''}</span>${control}</label>`;
function itemRow(item,path,index){
  const summary = `${item.q === 'n' ? 'per notte' : 'fisso'} · ${item.w || 0} g`;
  return `<details class="admin-item" data-path="${path}" data-index="${index}" data-search="${esc(`${item.n} ${item.cat}`.toLowerCase())}">
    <summary class="admin-item-title"><span><strong>${esc(item.n || 'Nuovo item')}</strong><small>${esc(item.cat || 'Senza categoria')}</small></span><em>${esc(summary)}</em><i aria-hidden="true">⌄</i></summary>
    <div class="admin-item-fields">
      ${field('Nome item', `<input data-f="n" value="${esc(item.n)}" required placeholder="Es. Giacca leggera">`)}
      ${field('Categoria', `<input data-f="cat" value="${esc(item.cat)}" placeholder="Es. Abbigliamento">`)}
      ${field('Quantità', `<select data-f="q"><option value="f" ${item.q==='f'?'selected':''}>Fissa</option><option value="n" ${item.q==='n'?'selected':''}>Per notte</option></select>`, 'Fissa o moltiplicata per notte')}
      ${field('Genere', `<select data-f="s">${[['U','Unisex'],['M','Uomo'],['F','Donna']].map(([x,l])=>`<option value="${x}" ${item.s===x?'selected':''}>${l}</option>`)}</select>`)}
      ${field('Peso', `<div class="admin-unit"><input data-f="w" type="number" min="0" value="${item.w}"><span>g</span></div>`, 'Grammi per singolo pezzo')}
      ${field('Importanza', `<select data-f="v">${[1,2,3].map(x=>`<option value="${x}" ${item.v===x?'selected':''}>${x} · ${['Essenziale','Utile','Opzionale'][x-1]}</option>`)}</select>`, 'Essenziale: quasi sempre necessario · Utile: consigliato · Opzionale: solo in casi specifici')}
      ${field('Ingombro', `<select data-f="bulk">${[1,2,3].map(x=>`<option value="${x}" ${Number(item.bulk||1)===x?'selected':''}>${x} · ${['Ridotto','Medio','Grande'][x-1]}</option>`)}</select>`)}
      <label class="admin-toggle"><input data-f="worn" type="checkbox" ${item.worn?'checked':''}><span><strong>Indossato</strong><small>Non pesa nel bagaglio</small></span></label>
      <details class="admin-transport"><summary>Mezzi compatibili <b>${item.transportModes.includes('tutti')?'Tutti i mezzi':item.transportModes.map(mode=>TRANSPORT_MODES.find(([value])=>value===mode)?.[1]).filter(Boolean).join(' + ')}</b></summary><div>${TRANSPORT_MODES.map(([value,label])=>`<label><input type="checkbox" data-transport-mode="${value}" ${item.transportModes.includes(value)?'checked':''}><span>${label}</span></label>`).join('')}</div></details>
      <details class="admin-weather"><summary>Meteo compatibili <b>${item.weatherModes.includes('tutti')?'Tutti i meteo':item.weatherModes.map(mode=>WEATHER_MODES.find(([value])=>value===mode)?.[1]).filter(Boolean).join(' + ')}</b></summary><div>${WEATHER_MODES.map(([value,label])=>`<label><input type="checkbox" data-weather-mode="${value}" ${item.weatherModes.includes(value)?'checked':''}><span>${label}</span></label>`).join('')}</div></details>
      <fieldset class="admin-quantity"><legend>Regola quantità <small>Calcolo automatico in base ai giorni</small></legend>
        ${field('Tipo', `<select data-quantity="type"><option value="fixed" ${item.quantityRule.type==='fixed'?'selected':''}>Quantità fissa</option><option value="perDay" ${item.quantityRule.type==='perDay'?'selected':''}>In base ai giorni</option></select>`)}
        ${field('Pezzi', `<input data-quantity="base" type="number" min="1" value="${item.quantityRule.base}">`)}
        ${field('Ogni X giorni', `<input data-quantity="every" type="number" min="1" value="${item.quantityRule.every}">`, 'Usato per il calcolo ceil(giorni / X)')}
        ${field('Minimo', `<input data-quantity="min" type="number" min="0" value="${item.quantityRule.min}">`)}
        ${field('Massimo', `<input data-quantity="max" type="number" min="0" value="${item.quantityRule.max}">`, '0 = nessun massimo')}
        <label class="admin-toggle"><input data-quantity="laundry" type="checkbox" ${item.quantityRule.laundry?'checked':''}><span><strong>Riducibile con lavanderia</strong><small>Usa frequenza e buffer lavanderia</small></span></label>
      </fieldset>
      <button data-action="delete-item" class="admin-delete">🗑 Elimina item</button>
    </div>
  </details>`;
}
function render(){
 const sections=pathList().map(([label,path])=>`<details class="admin-section" data-section="${path}"><summary><span>${esc(label)}</span><b>${getList(path).length} item</b></summary><div class="admin-items"><button data-action="add-item" data-path="${path}" class="admin-add">＋ Aggiungi item in ${esc(label)}</button>${getList(path).map((x,i)=>itemRow(x,path,i)).join('')}</div></details>`).join('');
 const acts=Object.keys(draft.db.extra).map(k=>`<div class="admin-rule"><label class="admin-field"><span>Chiave attività</span><input value="${esc(k)}" data-activity="${esc(k)}"></label><label class="admin-toggle"><input type="checkbox" data-pernight="${esc(k)}" ${draft.perNight.includes(k)?'checked':''}><span><strong>Per notte</strong></span></label><button data-action="delete-activity" data-key="${esc(k)}" class="admin-delete">Elimina</button></div>`).join('');
 const cats=[...new Set(itemLists(draft.db).flat().map(i=>i.cat))].sort().map(c=>`<div class="admin-rule"><label class="admin-field"><span>Nome categoria</span><input value="${esc(c)}" data-category="${esc(c)}"></label><button data-action="rename-category" data-key="${esc(c)}">Rinomina ovunque</button></div>`).join('');
 const rules=draft.daytripExclude.map((n,i)=>`<div class="admin-rule"><label class="admin-field"><span>Nome item escluso</span><input data-daytrip="${i}" value="${esc(n)}"></label><button data-action="delete-daytrip" data-index="${i}" class="admin-delete">Rimuovi</button></div>`).join('');
 shell('Gestione database',`<div class="admin-topbar"><div class="admin-unsaved">● Nessuna modifica</div><label class="admin-search">🔎<input id="adminSearch" placeholder="Cerca item o categoria…"></label></div><nav class="admin-tabs" aria-label="Sezioni amministrazione"><button type="button" data-tab="items" class="active">Items</button><button type="button" data-tab="activities">Attività</button><button type="button" data-tab="categories">Categorie</button><button type="button" data-tab="rules">Regole</button><button type="button" data-tab="communications">Comunicazioni</button></nav><main class="admin-content"><section data-page="items"><p class="admin-help">Apri una sezione e modifica i campi. Ogni valore è accompagnato dalla sua descrizione.</p>${sections}</section><section data-page="activities" hidden>${acts}<button data-action="add-activity" class="admin-add">＋ Nuova attività</button></section><section data-page="categories" hidden>${cats}</section><section data-page="rules" hidden><h3>Esclusioni gita giornaliera</h3><p class="admin-help">Questi item non vengono aggiunti quando il viaggio dura zero notti.</p>${rules}<button data-action="add-daytrip" class="admin-add">＋ Aggiungi nome</button><h3>Messaggi warning</h3>${draft.warningMessages.map((m,i)=>`<label class="admin-field admin-warning"><span>Warning ${i+1}</span><textarea data-warning="${i}">${esc(m)}</textarea></label>`).join('')}</section><section data-page="communications" hidden>${renderAdminCommunicationPanel()}</section></main><footer class="admin-save"><button data-action="preview" class="btn-secondary">Anteprima dati</button><span class="admin-status"></span><button data-action="save" class="btn-sm">Salva tutto</button></footer>`); bind();bindAdminCommunicationPanel();
}
function changed(){dirty=true; const x=document.querySelector('.admin-unsaved'); if(x){x.textContent='● Modifiche non salvate';x.classList.add('dirty')}}
function markModified(target) {
 const container = target.closest('.admin-field, .admin-toggle, .admin-rule');
 if (container) container.classList.add('is-modified');
}
function bind(){
 const modal=document.getElementById('adminModal');
 modal.oninput=e=>{if(e.target.id==='adminSearch'){const q=e.target.value.toLowerCase();document.querySelectorAll('.admin-item').forEach(x=>x.hidden=!x.dataset.search.includes(q));document.querySelectorAll('.admin-section').forEach(x=>{x.open=Boolean(q)||x.open});return}const row=e.target.closest('.admin-item');if(row&&e.target.dataset.f){const it=getList(row.dataset.path)[row.dataset.index],f=e.target.dataset.f;it[f]=f==='w'?Number(e.target.value):['v','bulk'].includes(f)?Number(e.target.value):f==='worn'?e.target.checked:e.target.value;row.querySelector('.admin-item-title strong').textContent=it.n||'Nuovo item';row.querySelector('.admin-item-title small').textContent=it.cat||'Senza categoria'}if(row&&e.target.dataset.quantity){const rule=getList(row.dataset.path)[row.dataset.index].quantityRule,key=e.target.dataset.quantity;rule[key]=key==='type'?e.target.value:key==='laundry'?e.target.checked:Number(e.target.value);markModified(e.target);changed();return}if(row&&e.target.dataset.transportMode){const item=getList(row.dataset.path)[row.dataset.index],mode=e.target.dataset.transportMode,group=e.target.closest('.admin-transport');if(mode==='tutti'&&e.target.checked)item.transportModes=['tutti'];else{item.transportModes=item.transportModes.filter(x=>x!=='tutti'&&x!==mode);if(e.target.checked)item.transportModes.push(mode);if(!item.transportModes.length)item.transportModes=['tutti']}group.querySelectorAll('[data-transport-mode]').forEach(input=>{input.checked=item.transportModes.includes(input.dataset.transportMode)});group.querySelector('summary b').textContent=item.transportModes.includes('tutti')?'Tutti i mezzi':item.transportModes.map(x=>TRANSPORT_MODES.find(([v])=>v===x)?.[1]).filter(Boolean).join(' + ');group.classList.add('is-modified');changed();return}if(row&&e.target.dataset.weatherMode){const item=getList(row.dataset.path)[row.dataset.index],mode=e.target.dataset.weatherMode,group=e.target.closest('.admin-weather');if(mode==='tutti'&&e.target.checked)item.weatherModes=['tutti'];else{item.weatherModes=item.weatherModes.filter(x=>x!=='tutti'&&x!==mode);if(e.target.checked)item.weatherModes.push(mode);if(!item.weatherModes.length)item.weatherModes=['tutti']}group.querySelectorAll('[data-weather-mode]').forEach(input=>{input.checked=item.weatherModes.includes(input.dataset.weatherMode)});group.querySelector('summary b').textContent=item.weatherModes.includes('tutti')?'Tutti i meteo':item.weatherModes.map(x=>WEATHER_MODES.find(([v])=>v===x)?.[1]).filter(Boolean).join(' + ');group.classList.add('is-modified');changed();return}if(e.target.dataset.warning!==undefined)draft.warningMessages[e.target.dataset.warning]=e.target.value;if(e.target.dataset.daytrip!==undefined)draft.daytripExclude[e.target.dataset.daytrip]=e.target.value;if(e.target.dataset.pernight!==undefined){const k=e.target.dataset.pernight;draft.perNight=e.target.checked?[...new Set([...draft.perNight,k])]:draft.perNight.filter(x=>x!==k)}markModified(e.target);changed()};
 modal.onclick=handleClick; modal.onchange=e=>{if(e.target.dataset.activity){const old=e.target.dataset.activity,next=e.target.value.trim();if(next!==old&&/^[a-z0-9_]+$/.test(next)&&!draft.db.extra[next]){draft.db.extra[next]=draft.db.extra[old];delete draft.db.extra[old];draft.perNight=draft.perNight.map(x=>x===old?next:x);changed();render();}else e.target.value=old;}};
}
function handleClick(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){document.querySelectorAll('[data-page]').forEach(x=>x.hidden=x.dataset.page!==b.dataset.tab);document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('.admin-topbar').hidden=b.dataset.tab!=='items';return}const a=b.dataset.action;if(!a)return;if(a==='add-item'){getList(b.dataset.path).unshift({n:'',q:'f',cat:'Varie',s:'U',w:0,v:1,worn:false,bulk:1,transportModes:['tutti'],weatherModes:['tutti'],quantityRule:{type:'fixed',base:1,every:1,min:1,max:0,laundry:false}});changed();render();const section=document.querySelector(`[data-section="${b.dataset.path}"]`);section.open=true;const first=section.querySelector('.admin-item');if(first)first.open=true;section.querySelector('[data-f="n"]').focus();return}if(a==='delete-item'&&confirm('Eliminare definitivamente questo item?'))getList(b.closest('.admin-item').dataset.path).splice(b.closest('.admin-item').dataset.index,1);if(a==='add-activity'){const k=prompt('Chiave attività (solo lettere minuscole, numeri e underscore):');if(k&&/^[a-z0-9_]+$/.test(k)&&!draft.db.extra[k])draft.db.extra[k]=[]}if(a==='delete-activity'&&confirm('Eliminare attività e relativi item?')){delete draft.db.extra[b.dataset.key];draft.perNight=draft.perNight.filter(x=>x!==b.dataset.key)}if(a==='rename-category'){const old=b.dataset.key,n=b.previousElementSibling.querySelector('input').value.trim();if(n&&confirm(`Rinominare “${old}” in “${n}” in tutti gli item?`))itemLists(draft.db).flat().forEach(i=>{if(i.cat===old)i.cat=n})}if(a==='add-daytrip')draft.daytripExclude.unshift('');if(a==='delete-daytrip'&&confirm('Rimuovere questa regola?'))draft.daytripExclude.splice(b.dataset.index,1);if(a==='preview')alert(JSON.stringify(payload(),null,2));if(a==='save'){document.getElementById('communicationSettingsForm')?.requestSubmit();return save(b)}changed();render()}
async function save(button){button.disabled=true;button.textContent='Salvataggio…';const status=document.querySelector('.admin-status');try{const r=await fetch('/api/update-db',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password,data:payload()})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Salvataggio non riuscito');dirty=false;document.querySelector('.admin-unsaved').textContent='✓ Tutte le modifiche applicate';document.querySelector('.admin-unsaved').className='admin-unsaved saved';status.textContent='Commit creato. Il deploy partirà a breve.';button.textContent='Salvato ✓'}catch(e){status.textContent=e.message;button.disabled=false;button.textContent='Salva tutto'}}
