import { DB, DAYTRIP_EXCLUDE, PER_NIGHT, WARNINGS } from './db.js';

let password = ''; let draft = null; let dirty = false;
const clone = value => structuredClone(value);
const itemLists = data => [data.base, data.laundry, ...Object.values(data.weather), ...Object.values(data.transport), ...Object.values(data.extra)];
const payload = () => ({ db: draft.db, daytripExclude: draft.daytripExclude, perNight: draft.perNight, warningMessages: draft.warningMessages });
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function initAdmin() {
  document.getElementById('adminOpen')?.addEventListener('click', openLogin);
}
function shell(title, body) {
  document.getElementById('adminModal')?.remove();
  document.body.insertAdjacentHTML('beforeend', `<div class="admin-modal" id="adminModal"><section class="admin-panel" role="dialog" aria-modal="true"><header><div><small>PACKLIST PRO</small><h2>${title}</h2></div><button class="admin-close" aria-label="Chiudi">×</button></header>${body}</section></div>`);
  const modal=document.getElementById('adminModal'); modal.querySelector('.admin-close').onclick=()=>{if(!dirty||confirm('Chiudere e perdere le modifiche non salvate?'))modal.remove()};
}
function openLogin() {
  shell('Accesso amministratore', `<form id="adminLogin" class="admin-login"><label>Password<input name="password" type="password" required autocomplete="current-password"></label><button class="btn-sm">Apri pannello</button><p class="admin-status"></p></form>`);
  document.getElementById('adminLogin').onsubmit = e => { e.preventDefault(); password=new FormData(e.target).get('password'); draft={db:clone(DB),daytripExclude:[...DAYTRIP_EXCLUDE],perNight:[...PER_NIGHT],warningMessages:WARNINGS.map(w=>w.msg)}; itemLists(draft.db).flat().forEach(item => { item.worn = Boolean(item.worn); item.bulk = Number(item.bulk || 1); }); dirty=false; render(); };
}
const pathList = () => [['Base','base'],['Laundry','laundry'],...Object.keys(draft.db.weather).map(k=>[`Weather · ${k}`,`weather.${k}`]),...Object.keys(draft.db.transport).map(k=>[`Transport · ${k}`,`transport.${k}`]),...Object.keys(draft.db.extra).map(k=>[`Attività · ${k}`,`extra.${k}`])];
const getList = path => path.split('.').reduce((o,k)=>o[k],draft.db);
function itemRow(item,path,index){return `<div class="admin-item" data-path="${path}" data-index="${index}"><input data-f="n" value="${esc(item.n)}" required placeholder="Nome"><input data-f="cat" value="${esc(item.cat)}" placeholder="Categoria"><select data-f="q"><option value="f" ${item.q==='f'?'selected':''}>Fissa</option><option value="n" ${item.q==='n'?'selected':''}>Per notte</option></select><select data-f="s">${['U','M','F'].map(x=>`<option ${item.s===x?'selected':''}>${x}</option>`)}</select><input data-f="w" type="number" min="0" value="${item.w}"><select data-f="v">${[1,2,3].map(x=>`<option ${item.v===x?'selected':''}>${x}</option>`)}</select><select data-f="bulk">${[1,2,3].map(x=>`<option ${Number(item.bulk||1)===x?'selected':''}>Ing. ${x}</option>`)}</select><label class="admin-check"><input data-f="worn" type="checkbox" ${item.worn?'checked':''}>Indossato</label><button data-action="delete-item" class="admin-danger">Elimina</button></div>`}
function render(){
 const sections=pathList().map(([label,path])=>`<details><summary>${esc(label)} <b>${getList(path).length}</b></summary><div class="admin-items">${getList(path).map((x,i)=>itemRow(x,path,i)).join('')}<button data-action="add-item" data-path="${path}" class="btn-secondary">+ Aggiungi item</button></div></details>`).join('');
 const acts=Object.keys(draft.db.extra).map(k=>`<div class="admin-rule"><input value="${esc(k)}" data-activity="${esc(k)}"><label><input type="checkbox" data-pernight="${esc(k)}" ${draft.perNight.includes(k)?'checked':''}> Per notte</label><button data-action="delete-activity" data-key="${esc(k)}" class="admin-danger">Elimina</button></div>`).join('');
 const cats=[...new Set(itemLists(draft.db).flat().map(i=>i.cat))].sort().map(c=>`<div class="admin-rule"><input value="${esc(c)}" data-category="${esc(c)}"><button data-action="rename-category" data-key="${esc(c)}">Rinomina</button></div>`).join('');
 const rules=draft.daytripExclude.map((n,i)=>`<div class="admin-rule"><input data-daytrip="${i}" value="${esc(n)}"><button data-action="delete-daytrip" data-index="${i}" class="admin-danger">Rimuovi</button></div>`).join('');
 shell('Gestione database',`<div class="admin-unsaved">● Nessuna modifica</div><nav class="admin-tabs"><button data-tab="items">Items</button><button data-tab="activities">Attività</button><button data-tab="categories">Categorie</button><button data-tab="rules">Regole</button></nav><main class="admin-content"><section data-page="items">${sections}</section><section data-page="activities" hidden>${acts}<button data-action="add-activity" class="btn-secondary">+ Nuova attività</button></section><section data-page="categories" hidden>${cats}</section><section data-page="rules" hidden><h3>DAYTRIP_EXCLUDE</h3>${rules}<button data-action="add-daytrip" class="btn-secondary">+ Aggiungi nome</button><h3>Messaggi warning</h3>${draft.warningMessages.map((m,i)=>`<textarea data-warning="${i}">${esc(m)}</textarea>`).join('')}</section></main><footer class="admin-save"><button data-action="preview" class="btn-secondary">Anteprima</button><span class="admin-status"></span><button data-action="save" class="btn-sm">Salva tutto</button></footer>`); bind();
}
function changed(){dirty=true; const x=document.querySelector('.admin-unsaved'); if(x){x.textContent='● Modifiche non salvate';x.classList.add('dirty')}}
function bind(){const modal=document.getElementById('adminModal'); modal.oninput=e=>{const row=e.target.closest('.admin-item');if(row&&e.target.dataset.f){const it=getList(row.dataset.path)[row.dataset.index],f=e.target.dataset.f;it[f]=f==='w'?Number(e.target.value):['v','bulk'].includes(f)?Number(e.target.value):f==='worn'?e.target.checked:e.target.value}if(e.target.dataset.warning!==undefined)draft.warningMessages[e.target.dataset.warning]=e.target.value;if(e.target.dataset.daytrip!==undefined)draft.daytripExclude[e.target.dataset.daytrip]=e.target.value;if(e.target.dataset.pernight!==undefined){const k=e.target.dataset.pernight;draft.perNight=e.target.checked?[...new Set([...draft.perNight,k])]:draft.perNight.filter(x=>x!==k)}changed()}; modal.onclick=handleClick; modal.onchange=e=>{if(e.target.dataset.activity){const old=e.target.dataset.activity,next=e.target.value.trim();if(next!==old&&/^[a-z0-9_]+$/.test(next)&&!draft.db.extra[next]){draft.db.extra[next]=draft.db.extra[old];delete draft.db.extra[old];draft.perNight=draft.perNight.map(x=>x===old?next:x);changed();render();}else e.target.value=old;}};}
function handleClick(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){document.querySelectorAll('[data-page]').forEach(x=>x.hidden=x.dataset.page!==b.dataset.tab);return}const a=b.dataset.action;if(!a)return;if(a==='add-item')getList(b.dataset.path).push({n:'Nuovo item',q:'f',cat:'Varie',s:'U',w:0,v:1,worn:false,bulk:1});if(a==='delete-item'&&confirm('Eliminare questo item?'))getList(b.closest('.admin-item').dataset.path).splice(b.closest('.admin-item').dataset.index,1);if(a==='add-activity'){const k=prompt('Chiave attività (lettere, numeri, underscore):');if(k&&/^[a-z0-9_]+$/.test(k)&&!draft.db.extra[k])draft.db.extra[k]=[]}if(a==='delete-activity'&&confirm('Eliminare attività e relativi item?')){delete draft.db.extra[b.dataset.key];draft.perNight=draft.perNight.filter(x=>x!==b.dataset.key)}if(a==='rename-category'){const old=b.dataset.key,n=b.previousElementSibling.value.trim();if(n&&confirm(`Rinominare “${old}” in “${n}”?`))itemLists(draft.db).flat().forEach(i=>{if(i.cat===old)i.cat=n})}if(a==='add-daytrip')draft.daytripExclude.push('Nuovo item');if(a==='delete-daytrip'&&confirm('Rimuovere questa regola?'))draft.daytripExclude.splice(b.dataset.index,1);if(a==='preview')alert(JSON.stringify(payload(),null,2));if(a==='save')return save(b);changed();render()}
async function save(button){button.disabled=true;button.textContent='Salvataggio…';const status=document.querySelector('.admin-status');try{const r=await fetch('/api/update-db',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password,data:payload()})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Salvataggio non riuscito');dirty=false;status.textContent='Commit creato. Il deploy partirà a breve.';button.textContent='Salvato ✓'}catch(e){status.textContent=e.message;button.disabled=false;button.textContent='Salva tutto'}}
