const SETTINGS_KEY='packlist_communication_settings',FEEDBACK_KEY='packlist_feedback_inbox',ANNOUNCEMENT_KEY='packlist_announcement_dismissed',SUPPORT_KEY='packlist_support_dismissed';
export const DEFAULT_COMMUNICATION_SETTINGS={announcement:{enabled:false,title:'',message:'',type:'info',ctaLabel:'',ctaUrl:'',dismissible:true},supportBanner:{enabled:false,title:'Ti è utile Packlist Pro?',message:'Offrimi un caffè per aiutarmi a migliorarla e mantenerla gratuita.',ctaLabel:'Supporta l’app',ctaUrl:'',position:'afterGenerate',dismissible:true,frequency:'weekly'},feedback:{enabled:true,categories:['Bug','Suggerimento','Problema lista','Richiesta funzione','Altro']}};
let context={state:null,version:''};
const clone=v=>structuredClone(v),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
const mergeSettings=value=>({announcement:{...DEFAULT_COMMUNICATION_SETTINGS.announcement,...value?.announcement},supportBanner:{...DEFAULT_COMMUNICATION_SETTINGS.supportBanner,...value?.supportBanner},feedback:{...DEFAULT_COMMUNICATION_SETTINGS.feedback,...value?.feedback}});
export const getDefaultCommunicationSettings=()=>clone(DEFAULT_COMMUNICATION_SETTINGS);
export const loadCommunicationSettings=()=>mergeSettings(read(SETTINGS_KEY,{}));
export function saveCommunicationSettings(settings){const ok=write(SETTINGS_KEY,mergeSettings(settings));renderAnnouncementBanner();renderSupportBanner(loadCommunicationSettings().supportBanner.position);return ok}
export function resetCommunicationSettings(){try{localStorage.removeItem(SETTINGS_KEY)}catch{}return getDefaultCommunicationSettings()}
export const getFeedbackInbox=()=>{const list=read(FEEDBACK_KEY,[]);return Array.isArray(list)?list:[]};
export function saveFeedback(feedback){const item={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,createdAt:new Date().toISOString(),rating:Number(feedback.rating),category:String(feedback.category),message:String(feedback.message).trim(),email:String(feedback.email||'').trim(),appVersion:context.version,userAgent:navigator.userAgent||'',online:navigator.onLine!==false,config:(({nights,gender,transport,transports,weather,activities,laundry,laundryFreq,laundryBuffer})=>({nights,gender,transport,transports,weather,activities,laundry,laundryFreq,laundryBuffer}))(context.state?.config||{})};const list=getFeedbackInbox();list.unshift(item);write(FEEDBACK_KEY,list);return item}
export function deleteFeedback(id){return write(FEEDBACK_KEY,getFeedbackInbox().filter(item=>item.id!==id))}
export function clearFeedbackInbox(){return write(FEEDBACK_KEY,[])}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
export function exportFeedbackJSON(){download('packlist-feedback.json',JSON.stringify(getFeedbackInbox(),null,2),'application/json')}
export function exportFeedbackCSV(){const rows=[['createdAt','rating','category','message','email','appVersion'],...getFeedbackInbox().map(x=>[x.createdAt,x.rating,x.category,x.message,x.email,x.appVersion])];download('packlist-feedback.csv',rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
function bannerHtml(kind,data,closeAction){return `<aside class="communication-banner ${kind}" role="status"><div><strong>${esc(data.title)}</strong><span>${esc(data.message)}</span></div>${data.ctaUrl&&data.ctaLabel?`<a class="btn-sm" href="${esc(data.ctaUrl)}" target="_blank" rel="noopener">${esc(data.ctaLabel)}</a>`:''}${data.dismissible?`<button type="button" data-communication-close="${closeAction}" aria-label="Chiudi">×</button>`:''}</aside>`}
export function renderAnnouncementBanner(){const mount=document.getElementById('announcementMount');if(!mount)return;const a=loadCommunicationSettings().announcement,dismissed=read(ANNOUNCEMENT_KEY,'');const signature=`${a.title}|${a.message}|${a.ctaUrl}`;mount.innerHTML=a.enabled&&dismissed!==signature?bannerHtml(a.type,a,'announcement'):''}
export function shouldShowSupportBanner(){const s=loadCommunicationSettings().supportBanner;if(!s.enabled)return false;const last=Number(read(SUPPORT_KEY,0));if(s.frequency==='always')return true;if(s.frequency==='once')return !last;return Date.now()-last>(s.frequency==='daily'?864e5:6048e5)}
export function dismissSupportBanner(){write(SUPPORT_KEY,Date.now());document.querySelectorAll('.support-banner').forEach(x=>x.remove())}
export function renderSupportBanner(position='top'){const s=loadCommunicationSettings().supportBanner;for(const id of ['supportTopMount','supportAfterGenerateMount','supportFooterMount']){const m=document.getElementById(id);if(m)m.innerHTML=''}if(s.position!==position||!shouldShowSupportBanner()||(position==='afterGenerate'&&!Object.keys(context.state?.list||{}).length))return;const mount=document.getElementById({top:'supportTopMount',afterGenerate:'supportAfterGenerateMount',footer:'supportFooterMount'}[position]);if(mount)mount.innerHTML=bannerHtml('support support-banner',s,'support')}
export function openFeedbackModal(){const settings=loadCommunicationSettings();if(!settings.feedback.enabled)return;document.getElementById('feedbackModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop feedback-modal open" id="feedbackModal" aria-hidden="false"><form class="item-options-card" id="feedbackForm" role="dialog" aria-modal="true"><div class="item-options-head"><h2>Lascia feedback</h2><button type="button" class="modal-close" data-feedback-close>×</button></div><label class="option-field">Valutazione<select name="rating">${[5,4,3,2,1].map(x=>`<option value="${x}">${x} / 5</option>`)}</select></label><label class="option-field">Categoria<select name="category">${settings.feedback.categories.map(x=>`<option>${esc(x)}</option>`)}</select></label><label class="option-field">Messaggio<textarea name="message" required></textarea></label><label class="option-field">Email opzionale<input name="email" type="email"></label><p class="communication-note"></p><div class="modal-actions"><button type="button" class="btn-secondary" data-feedback-close>Annulla</button><button class="btn-sm">Salva localmente</button></div></form></div>`);const modal=document.getElementById('feedbackModal'),close=()=>modal.remove();modal.querySelectorAll('[data-feedback-close]').forEach(x=>x.onclick=close);modal.onkeydown=e=>{if(e.key==='Escape')close()};modal.querySelector('form').onsubmit=e=>{e.preventDefault();saveFeedback(Object.fromEntries(new FormData(e.target)));modal.querySelector('.communication-note').textContent='Feedback salvato localmente. Per riceverlo realmente serve configurare un backend/API.'};modal.querySelector('textarea').focus()}
export function initCommunications({state,version}){context={state,version};document.addEventListener('click',e=>{const action=e.target.closest?.('[data-communication-close]')?.dataset.communicationClose;if(action==='announcement'){const a=loadCommunicationSettings().announcement;write(ANNOUNCEMENT_KEY,`${a.title}|${a.message}|${a.ctaUrl}`);renderAnnouncementBanner()}if(action==='support')dismissSupportBanner()});renderAnnouncementBanner();renderSupportBanner(loadCommunicationSettings().supportBanner.position)}
const input=(label,name,value,type='text')=>`<label class="admin-field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}"></label>`;
export function renderAdminCommunicationPanel(){const s=loadCommunicationSettings(),feedback=getFeedbackInbox();return `<div class="admin-communications"><p class="communication-note">Queste impostazioni sono locali su questo dispositivo. Per renderle globali serve una futura API dedicata.</p><form id="communicationSettingsForm"><h3>Annuncio app</h3><label class="admin-toggle"><input name="announcement.enabled" type="checkbox" ${s.announcement.enabled?'checked':''}><span><strong>Attivo</strong></span></label>${input('Titolo','announcement.title',s.announcement.title)}${input('Messaggio','announcement.message',s.announcement.message)}${input('Tipo','announcement.type',s.announcement.type)}${input('CTA label','announcement.ctaLabel',s.announcement.ctaLabel)}${input('CTA URL','announcement.ctaUrl',s.announcement.ctaUrl,'url')}<label class="admin-toggle"><input name="announcement.dismissible" type="checkbox" ${s.announcement.dismissible?'checked':''}><span><strong>Chiudibile</strong></span></label><h3>Banner supporto</h3><label class="admin-toggle"><input name="supportBanner.enabled" type="checkbox" ${s.supportBanner.enabled?'checked':''}><span><strong>Attivo</strong></span></label>${input('Titolo','supportBanner.title',s.supportBanner.title)}${input('Messaggio','supportBanner.message',s.supportBanner.message)}${input('CTA label','supportBanner.ctaLabel',s.supportBanner.ctaLabel)}${input('CTA URL','supportBanner.ctaUrl',s.supportBanner.ctaUrl,'url')}<label class="admin-toggle"><input name="supportBanner.dismissible" type="checkbox" ${s.supportBanner.dismissible?'checked':''}><span><strong>Chiudibile</strong></span></label><label class="admin-field"><span>Posizione</span><select name="supportBanner.position">${['top','afterGenerate','footer'].map(x=>`<option ${s.supportBanner.position===x?'selected':''}>${x}</option>`)}</select></label><label class="admin-field"><span>Frequenza</span><select name="supportBanner.frequency">${['always','daily','weekly','once'].map(x=>`<option ${s.supportBanner.frequency===x?'selected':''}>${x}</option>`)}</select></label><button class="btn-sm">Salva impostazioni locali</button></form><h3>Feedback ricevuti (${feedback.length})</h3><div class="admin-feedback-actions"><button data-comm-action="json">Esporta JSON</button><button data-comm-action="csv">Esporta CSV</button><button data-comm-action="clear">Svuota</button></div><div class="admin-feedback-list">${feedback.map(x=>`<article><strong>${esc(x.category)} · ${x.rating}/5</strong><p>${esc(x.message)}</p><button data-comm-delete="${x.id}">Elimina</button></article>`).join('')||'<p>Nessun feedback locale.</p>'}</div></div>`}
export function bindAdminCommunicationPanel(){const form=document.getElementById('communicationSettingsForm');if(form)form.onsubmit=e=>{e.preventDefault();const next=loadCommunicationSettings();for(const [key,value] of new FormData(form)){const [group,field]=key.split('.');next[group][field]=value}next.announcement.enabled=form.elements['announcement.enabled'].checked;next.supportBanner.enabled=form.elements['supportBanner.enabled'].checked;next.announcement.dismissible=form.elements['announcement.dismissible'].checked;next.supportBanner.dismissible=form.elements['supportBanner.dismissible'].checked;saveCommunicationSettings(next);form.querySelector('button').textContent='Salvato ✓'};document.querySelectorAll('[data-comm-delete]').forEach(b=>b.onclick=()=>{deleteFeedback(b.dataset.commDelete);b.closest('article').remove()});document.querySelector('[data-comm-action="json"]')?.addEventListener('click',exportFeedbackJSON);document.querySelector('[data-comm-action="csv"]')?.addEventListener('click',exportFeedbackCSV);document.querySelector('[data-comm-action="clear"]')?.addEventListener('click',()=>{if(confirm('Svuotare tutti i feedback locali?')){clearFeedbackInbox();document.querySelector('.admin-feedback-list').innerHTML='<p>Nessun feedback locale.</p>'}})}
