// Dati modificabili dal pannello amministratore. Non inserire segreti in questo file.

export const DB_DATA = {
  base: [
    {n:"Mutande",q:"n",cat:"Abbigliamento Base",s:"U",w:50,v:1},
    {n:"Calze",q:"n",cat:"Abbigliamento Base",s:"U",w:80,v:1},
    {n:"Canottiere/Sottogiacca",q:"n",cat:"Abbigliamento Base",s:"U",w:120,v:1},
    {n:"T-shirt",q:"n",cat:"Abbigliamento Base",s:"U",w:180,v:1},
    {n:"Pigiama",q:"f",cat:"Abbigliamento Base",s:"U",w:300,v:2},
    {n:"Pantaloni casual",q:"f",cat:"Abbigliamento Base",s:"U",w:400,v:2,worn:true},
    {n:"Documenti/Patente",q:"f",cat:"Essenziali",s:"U",w:30,v:1},
    {n:"Portafoglio/Contanti",q:"f",cat:"Essenziali",s:"U",w:100,v:1},
    {n:"Cellulare + Cavo",q:"f",cat:"Tech",s:"U",w:250,v:1},
    {n:"Powerbank",q:"f",cat:"Tech",s:"U",w:250,v:1},
    {n:"Multipresa viaggio",q:"f",cat:"Tech",s:"U",w:300,v:2},
    {n:"Cuffie",q:"f",cat:"Tech",s:"U",w:200,v:1},
    {n:"Spazzolino/Dentifricio",q:"f",cat:"Igiene",s:"U",w:80,v:1},
    {n:"Deodorante",q:"f",cat:"Igiene",s:"U",w:100,v:1},
    {n:"Tagliaunghie/Pinzetta",q:"f",cat:"Igiene",s:"U",w:50,v:1},
    {n:"Kit Barba",q:"f",cat:"Igiene",s:"M",w:200,v:1},
    {n:"Trucchi base",q:"f",cat:"Igiene",s:"F",w:300,v:2},
    {n:"Tachipirina/Oki",q:"f",cat:"Salute",s:"U",w:50,v:1},
    {n:"Cerotti assortiti",q:"f",cat:"Salute",s:"U",w:40,v:1},
    {n:"Disinfettante mani",q:"f",cat:"Salute",s:"U",w:100,v:1},
  ],
  laundry: [
    {n:"Detersivo monodose",q:"f",cat:"Igiene",s:"U",w:30,v:1},
    {n:"Filo stendino viaggio",q:"f",cat:"Accessori",s:"U",w:50,v:1},
    {n:"Sacchetto biancheria",q:"f",cat:"Accessori",s:"U",w:30,v:1},
  ],
  weather: {
    sun: [
      {n:"Occhiali da sole",q:"f",cat:"Accessori",s:"U",w:80,v:1},
      {n:"Crema solare SPF50",q:"f",cat:"Salute",s:"U",w:200,v:1},
      {n:"Cappellino",q:"f",cat:"Accessori",s:"U",w:100,v:1},
    ],
    rain: [
      {n:"Ombrello piccolo",q:"f",cat:"Accessori",s:"U",w:300,v:2},
      {n:"Guscio/Impermeabile",q:"f",cat:"Abbigliamento",s:"U",w:600,v:2},
      {n:"Scarpe waterproof",q:"f",cat:"Abbigliamento",s:"U",w:800,v:3},
      {n:"Sacca impermeabile",q:"f",cat:"Accessori",s:"U",w:150,v:1},
    ],
    cold: [
      {n:"Maglia termica",q:"f",cat:"Abbigliamento",s:"U",w:200,v:2},
      {n:"Guanti/Berretto",q:"f",cat:"Accessori",s:"U",w:150,v:1},
      {n:"Burrocacao",q:"f",cat:"Salute",s:"U",w:30,v:1},
      {n:"Sciarpa",q:"f",cat:"Accessori",s:"U",w:200,v:2},
      {n:"Giacca pesante",q:"f",cat:"Abbigliamento",s:"U",w:900,v:3,worn:true},
    ],
  },
  transport: {
    auto: [
      {n:"Occhiali guida",q:"f",cat:"Trasporto",s:"U",w:80,v:1},
      {n:"Cavo ricarica auto",q:"f",cat:"Tech",s:"U",w:150,v:1},
      {n:"Kit emergenza auto",q:"f",cat:"Trasporto",s:"U",w:400,v:2},
    ],
    moto: [
      {n:"Kit foratura",q:"f",cat:"Moto",s:"U",w:300,v:1},
      {n:"Grasso catena spray",q:"f",cat:"Moto",s:"U",w:200,v:1},
      {n:"Panno visiera",q:"f",cat:"Moto",s:"U",w:30,v:1},
      {n:"Bloccadisco",q:"f",cat:"Moto",s:"U",w:400,v:2},
      {n:"Guanti moto",q:"f",cat:"Moto",s:"U",w:300,v:2,worn:true},
    ],
    aereo: [
      {n:"Passaporto",q:"f",cat:"Essenziali",s:"U",w:50,v:1},
      {n:"Liquidi <100ml",q:"f",cat:"Igiene",s:"U",w:300,v:1},
      {n:"Tappi orecchie",q:"f",cat:"Comfort",s:"U",w:20,v:1},
      {n:"Adattatore prese",q:"f",cat:"Tech",s:"U",w:100,v:1},
      {n:"Cuscino viaggio",q:"f",cat:"Comfort",s:"U",w:200,v:3},
    ],
    backpack: [
      {n:"Sacco biancheria sporca",q:"f",cat:"Zaino",s:"U",w:60,v:1},
      {n:"Asciugamano microfibra",q:"f",cat:"Igiene",s:"U",w:200,v:2},
      {n:"Lucchetto TSA",q:"f",cat:"Zaino",s:"U",w:100,v:1},
      {n:"Coprizaino pioggia",q:"f",cat:"Zaino",s:"U",w:150,v:1},
    ],
  },
  extra: {
    trekking: [
      {n:"Scarponi trekking",q:"f",cat:"Trekking",s:"U",w:1200,v:3,worn:true},
      {n:"Calze trekking",q:"n",cat:"Trekking",s:"U",w:100,v:1},
      {n:"Borraccia 1L",q:"f",cat:"Trekking",s:"U",w:250,v:2},
      {n:"Coltellino multiuso",q:"f",cat:"Trekking",s:"U",w:120,v:1},
      {n:"Bastoncini",q:"f",cat:"Trekking",s:"U",w:400,v:3},
      {n:"Kit primo soccorso",q:"f",cat:"Salute",s:"U",w:200,v:1},
      {n:"Mappa/GPS",q:"f",cat:"Trekking",s:"U",w:80,v:1},
    ],
    nuoto: [
      {n:"Costume",q:"f",cat:"Nuoto",s:"U",w:200,v:1},
      {n:"Cuffia/Occhialini",q:"f",cat:"Nuoto",s:"U",w:80,v:1},
      {n:"Infradito",q:"f",cat:"Nuoto",s:"U",w:250,v:2},
      {n:"Telo mare",q:"f",cat:"Nuoto",s:"U",w:400,v:3},
      {n:"Maschera snorkeling",q:"f",cat:"Nuoto",s:"U",w:300,v:2},
    ],
    spiaggia: [
      {n:"Costume",q:"f",cat:"Spiaggia",s:"U",w:200,v:1},
      {n:"Infradito",q:"f",cat:"Spiaggia",s:"U",w:250,v:2},
      {n:"Telo mare",q:"f",cat:"Spiaggia",s:"U",w:400,v:3},
      {n:"Borsa termica",q:"f",cat:"Spiaggia",s:"U",w:300,v:3},
      {n:"Libro/Kindle",q:"f",cat:"Spiaggia",s:"U",w:250,v:1},
      {n:"Pareo",q:"f",cat:"Spiaggia",s:"U",w:150,v:1},
    ],
    lavoro: [
      {n:"Laptop + Caricatore",q:"f",cat:"Lavoro",s:"U",w:2200,v:2},
      {n:"Camicia",q:"n",cat:"Lavoro",s:"U",w:250,v:1},
      {n:"Agenda/Penne",q:"f",cat:"Lavoro",s:"U",w:200,v:1},
      {n:"Mouse/Tastiera",q:"f",cat:"Lavoro",s:"U",w:400,v:2},
      {n:"Adattatore HDMI",q:"f",cat:"Lavoro",s:"U",w:80,v:1},
    ],
    cena: [
      {n:"Abito elegante",q:"f",cat:"Abbigliamento",s:"U",w:500,v:2},
      {n:"Scarpe eleganti",q:"f",cat:"Abbigliamento",s:"U",w:700,v:3,worn:true},
      {n:"Profumo",q:"f",cat:"Igiene",s:"U",w:150,v:1},
      {n:"Cintura",q:"f",cat:"Abbigliamento",s:"U",w:100,v:1},
    ],
    ciclismo: [
      {n:"Casco ciclismo",q:"f",cat:"Ciclismo",s:"U",w:300,v:3,worn:true},
      {n:"Abbigliamento tecnico bici",q:"n",cat:"Ciclismo",s:"U",w:200,v:1},
      {n:"Guanti ciclismo",q:"f",cat:"Ciclismo",s:"U",w:80,v:1,worn:true},
      {n:"Kit riparazione bici",q:"f",cat:"Ciclismo",s:"U",w:250,v:1},
      {n:"Crema antifrizione",q:"f",cat:"Ciclismo",s:"U",w:100,v:1},
      {n:"Borraccia bici",q:"f",cat:"Ciclismo",s:"U",w:200,v:2},
    ],
    sport_invernali: [
      {n:"Tuta da sci",q:"f",cat:"Sport Invernali",s:"U",w:1500,v:3,worn:true},
      {n:"Casco sci/neve",q:"f",cat:"Sport Invernali",s:"U",w:400,v:3,worn:true},
      {n:"Occhiali da neve",q:"f",cat:"Sport Invernali",s:"U",w:150,v:2,worn:true},
      {n:"Calze termiche sci",q:"n",cat:"Sport Invernali",s:"U",w:120,v:1},
      {n:"Guanti sci",q:"f",cat:"Sport Invernali",s:"U",w:200,v:2,worn:true},
      {n:"Scaldacollo",q:"f",cat:"Sport Invernali",s:"U",w:80,v:1,worn:true},
      {n:"Crema protezione sole neve",q:"f",cat:"Salute",s:"U",w:150,v:1},
    ],
    moto_adv: [
      {n:"Tuta antipioggia intera",q:"f",cat:"Moto Pro",s:"U",w:800,v:3},
      {n:"Sottotuta tecnico",q:"f",cat:"Moto Pro",s:"U",w:350,v:2},
      {n:"Interfono carico",q:"f",cat:"Moto Pro",s:"U",w:150,v:1},
      {n:"Paragambe",q:"f",cat:"Moto Pro",s:"U",w:500,v:2},
    ],
    camping: [
      {n:"Tenda",q:"f",cat:"Camping",s:"U",w:2000,v:3},
      {n:"Sacco a pelo",q:"f",cat:"Camping",s:"U",w:1200,v:3},
      {n:"Tappetino isolante",q:"f",cat:"Camping",s:"U",w:500,v:3},
      {n:"Torcia frontale",q:"f",cat:"Camping",s:"U",w:100,v:1},
      {n:"Accendino",q:"f",cat:"Camping",s:"U",w:20,v:1},
      {n:"Borraccia 1L",q:"f",cat:"Camping",s:"U",w:250,v:2},
      {n:"Kit cucina camping",q:"f",cat:"Camping",s:"U",w:600,v:3},
      {n:"Repellente insetti",q:"f",cat:"Salute",s:"U",w:150,v:1},
    ],
    foto: [
      {n:"Corpo macchina",q:"f",cat:"Fotografia",s:"U",w:700,v:2},
      {n:"Obiettivi extra",q:"f",cat:"Fotografia",s:"U",w:500,v:2},
      {n:"Schede SD extra",q:"f",cat:"Fotografia",s:"U",w:20,v:1},
      {n:"Batterie extra",q:"f",cat:"Fotografia",s:"U",w:100,v:1},
      {n:"Treppiede leggero",q:"f",cat:"Fotografia",s:"U",w:800,v:3},
      {n:"Kit pulizia lenti",q:"f",cat:"Fotografia",s:"U",w:80,v:1},
    ],
    fitness: [
      {n:"Scarpe running",q:"f",cat:"Fitness",s:"U",w:600,v:3,worn:true},
      {n:"Abbigliamento tecnico",q:"n",cat:"Fitness",s:"U",w:200,v:1},
      {n:"Fascia sudore",q:"f",cat:"Fitness",s:"U",w:40,v:1},
      {n:"Bracciale porta-telefono",q:"f",cat:"Fitness",s:"U",w:60,v:1},
      {n:"Asciugamano palestra",q:"f",cat:"Fitness",s:"U",w:150,v:2},
    ],
    bambini: [
      {n:"Pannolini",q:"n",cat:"Bambini",s:"U",w:50,v:2},
      {n:"Salviette umidificate",q:"f",cat:"Bambini",s:"U",w:150,v:2},
      {n:"Cambio vestiti bimbo",q:"n",cat:"Bambini",s:"U",w:300,v:2},
      {n:"Marsupio/Zaino bimbo",q:"f",cat:"Bambini",s:"U",w:800,v:3},
      {n:"Termometro",q:"f",cat:"Bambini",s:"U",w:50,v:1},
      {n:"Giochi viaggio",q:"f",cat:"Bambini",s:"U",w:200,v:2},
      {n:"Crema solare bimbi",q:"f",cat:"Salute",s:"U",w:150,v:1},
    ],
    alpinismo: [
      {n:"Corda (60m)",q:"f",cat:"Tecnico",s:"U",w:3600,v:3},
      {n:"Imbrago",q:"f",cat:"Tecnico",s:"U",w:450,v:2},
      {n:"Casco alpinismo",q:"f",cat:"Tecnico",s:"U",w:350,v:3,worn:true},
      {n:"Ramponi",q:"f",cat:"Tecnico",s:"U",w:900,v:2},
      {n:"Piccozza",q:"f",cat:"Tecnico",s:"U",w:500,v:2},
      {n:"Kit rinvii/moschettoni",q:"f",cat:"Tecnico",s:"U",w:800,v:2},
      {n:"Kit primo soccorso",q:"f",cat:"Tecnico",s:"U",w:200,v:1},
    ],
    ferrata: [
      {n:"Set Ferrata (Y-longe)",q:"f",cat:"Tecnico",s:"U",w:550,v:2},
      {n:"Imbrago leggero",q:"f",cat:"Tecnico",s:"U",w:400,v:2},
      {n:"Casco (ferrata/alpinismo)",q:"f",cat:"Tecnico",s:"U",w:350,v:3,worn:true},
      {n:"Guanti da ferrata",q:"f",cat:"Tecnico",s:"U",w:100,v:1,worn:true},
      {n:"Moschettone a ghiera extra",q:"f",cat:"Tecnico",s:"U",w:80,v:1},
    ],
  }
};


export const DAYTRIP_EXCLUDE_DATA = [
  'Mutande','Calze','Canottiere/Sottogiacca','T-shirt','Pigiama','Pantaloni casual',
  'Spazzolino/Dentifricio','Deodorante','Tagliaunghie/Pinzetta','Kit Barba','Trucchi base',
  'Profumo','Laptop + Caricatore','Camicia','Agenda/Penne','Mouse/Tastiera','Adattatore HDMI',
  'Abito elegante','Scarpe eleganti','Cintura','Tenda','Sacco a pelo','Tappetino isolante',
  'Kit cucina camping','Pannolini','Cambio vestiti bimbo','Multipresa viaggio','Cuffie',
  'Cuscino viaggio','Disinfettante mani','Sacco biancheria sporca','Lucchetto TSA',
  'Detersivo monodose','Filo stendino viaggio','Sacchetto biancheria','Pigiama'
];

export const PER_NIGHT_DATA = ['trekking','nuoto','lavoro','fitness','ciclismo','sport_invernali','bambini','alpinismo','ferrata'];

export const WARNING_MESSAGES = [
  '✈️ Attenzione: il coltellino multiuso non è consentito in cabina',
  '✈️ Attenzione: gli accendini sono vietati in aereo',
  '🧺 Lavanderia non necessaria per gite in giornata',
  `👔 Viaggio lungo senza lavanderia: considera l'attivazione per ottimizzare i bagagli`,
];
