const buckets = new Map();
const allowedTop = new Set(['db','daytripExclude','perNight','warningMessages']);
const allowedItem = new Set(['n','q','cat','s','w','v','worn','bulk']);
const fixed = { weather:['sun','rain','cold'], transport:['auto','moto','aereo','backpack'] };
const fail = (res,status,error) => res.status(status).json({ok:false,error});
function exact(o, keys){return o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).every(k=>keys.has(k))&&[...keys].every(k=>k in o)}
function validItem(i){return i&&typeof i==='object'&&!Array.isArray(i)&&Object.keys(i).every(k=>allowedItem.has(k))&&typeof i.n==='string'&&i.n.trim()&&typeof i.cat==='string'&&['f','n'].includes(i.q)&&['U','M','F'].includes(i.s)&&typeof i.w==='number'&&Number.isFinite(i.w)&&i.w>=0&&[1,2,3].includes(i.v)&&typeof i.worn==='boolean'&&(i.bulk===undefined||[1,2,3].includes(i.bulk))}
const validList = x => Array.isArray(x)&&x.every(validItem);
function validate(data){if(!exact(data,allowedTop)||!exact(data.db,new Set(['base','laundry','weather','transport','extra']))||!validList(data.db.base)||!validList(data.db.laundry))return false;for(const [group,keys] of Object.entries(fixed)){if(!exact(data.db[group],new Set(keys))||!keys.every(k=>validList(data.db[group][k])))return false}if(!data.db.extra||typeof data.db.extra!=='object'||Array.isArray(data.db.extra)||!Object.keys(data.db.extra).every(k=>/^[a-z0-9_]+$/.test(k)&&validList(data.db.extra[k])))return false;return ['daytripExclude','perNight','warningMessages'].every(k=>Array.isArray(data[k])&&data[k].every(x=>typeof x==='string'))&&data.perNight.every(k=>k in data.db.extra)}
function serialize(d){return `// Dati modificabili dal pannello amministratore. Non inserire segreti in questo file.\n\nexport const DB_DATA = ${JSON.stringify(d.db,null,2)};\n\nexport const DAYTRIP_EXCLUDE_DATA = ${JSON.stringify(d.daytripExclude,null,2)};\n\nexport const PER_NIGHT_DATA = ${JSON.stringify(d.perNight,null,2)};\n\nexport const WARNING_MESSAGES = ${JSON.stringify(d.warningMessages,null,2)};\n`}
export default async function handler(req,res){if(req.method!=='POST')return fail(res,405,'Metodo non consentito');const ip=(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim(),now=Date.now(),hits=(buckets.get(ip)||[]).filter(t=>now-t<60000);if(hits.length>=10)return fail(res,429,'Troppe richieste. Riprova tra un minuto.');hits.push(now);buckets.set(ip,hits);if(!process.env.ADMIN_PASSWORD||req.body?.password!==process.env.ADMIN_PASSWORD)return fail(res,401,'Credenziali non valide');if(!validate(req.body?.data))return fail(res,400,'Dati non validi');const token=process.env.GITHUB_TOKEN,repo=process.env.GITHUB_REPO,branch=process.env.GITHUB_BRANCH||'main';if(!token||!repo)return fail(res,500,'Configurazione server incompleta');const path='js/modules/db-data.js',url=`https://api.github.com/repos/${repo}/contents/${path}`,headers={Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'packlist-pro-admin'};try{const current=await fetch(`${url}?ref=${encodeURIComponent(branch)}`,{headers});if(!current.ok)throw new Error(`lettura GitHub (${current.status})`);const {sha}=await current.json();const content=Buffer.from(serialize(req.body.data)).toString('base64');const update=await fetch(url,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({message:'chore: update packlist database from admin',content,sha,branch})});if(!update.ok)throw new Error(`commit GitHub (${update.status})`);return res.status(200).json({ok:true})}catch(e){console.error(e);return fail(res,502,'Impossibile aggiornare il database su GitHub')}}
